
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install dependencies and package Lambda
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt -t . # Install dependencies to the current directory
        zip -r test-dep-dev.zip . # Zip all files in the current directory

    - name: Deploy to AWS Lambda
      uses: appleboy/lambda-action@v0.0.4
      with:
        function_name: myLambda
        zip_file: test-dep-dev.zip